### ISSUE TITLE
support several hosts

### ISSUE THREAD

**Issue by vayser** [sapegin/shipit#11]
it will be perfect to have opportunity to deploy source at different hosts, I have stage and prod servers, how can I use shipit for both ?

**Comment by sapegin** [comment]
There’s no such ability now but you probably can do something like that:

```
host='prodhost'
path='sites/example.com'

[stage]
SSH_HOST='stagehost'
git checkout master
…

[prod]
git checkout master
…
```

I didn’t test it though ;-)
