### ISSUE TITLE
Prints corrupted character sequences on non-Unicode terminals

### ISSUE THREAD

**Issue by h3xx** [sapegin/shipit#15]
Script wrongly outputs utf8 characters to non-Unicode terminals. Here is a screenshot from xterm running without Unicode support, and locale settings for latin1 character set.

![screenshot-2015-0616-1106](https://cloud.githubusercontent.com/assets/615684/8187848/e95fa518-1417-11e5-9725-2b662866cf84.png)

Standard method of determining what character set the terminal supports is via the `LC_CTYPE` environment variable.

Here's a screenshot of how the character set of messages are supposed to interact with the locale settings.

![screenshot-2015-0616-1112](https://cloud.githubusercontent.com/assets/615684/8188404/5d2b0fca-141b-11e5-8950-2c55405646ee.png)

As you can see, when `LC_CTYPE` is fr_FR.utf8, Unicode characters are printed, but when `LC_CTYPE` is fr_FR, they're replaced with their latin1 equivalent.

**Comment by sapegin** [comment]
Good idea for pull request.

**Comment by h3xx** [comment]
Investigating how to solve it and running into the inevitability that the script will need a full-fledged gettext message library. See: second system effect.

But hey, if you do that, it'll support internationalization.

**Comment by sapegin** [comment]
This script definitely doesn’t need localization and anything like gettext.

**Comment by h3xx** [comment]
In that case, just use latin1 characters for your line art and it'll be fine.

**Comment by sapegin** [comment]
It’s fine for me and 99% users with utf8.

**Comment by h3xx** [comment]
![Works on My Machine](http://blog.codinghorror.com/content/images/uploads/2007/03/6a0120a85dcdae970b0128776ff992970c-pi.png)
