### ISSUE TITLE
Readme doesn't include non-standard port config or ssh key

### ISSUE THREAD

**Issue by aerth** [sapegin/shipit#16]
In the past I modified shipit to include a SSH_PORT and SSH_KEY in the .shipit config, but then I realized there is a much better way of doing it, without any hacks. Just open your ~/.ssh/config and make sure it is correctly filled in.

For example, in /home/user/.ssh/config:
host example.com
IdentityFile ~/.ssh/keyfile
port 10022
user usernamehere

We may wish to add something about this to the README because rarely do people use SSH on 22 without a keyfile. (But rarely are SSH users not aware of ~/.ssh/config). Just my 2 cents, thanks for an awesome thang.

**Comment by sapegin** [comment]
It would be great if you send a pull request for that ;-)

**Comment by aerth** [comment]
k no prob!
