### ISSUE TITLE
multiple hosts?

### ISSUE THREAD

**Issue by yitang** [sapegin/shipit#21]
Hi, I am building a cluster grid and I found shipit very useful. I wonder what's the best way to deploy to multiple hosts? Currently, I have to create multiple folders and each has .shiptit file, and I have to run shipit on each folder.

Yi

**Comment by sapegin** [comment]
I haven’t tried it but something like this may work:

```
host=$SHIPIT_HOST
path='sites/example.com'

[deploy]
git checkout master
...
```

And then you call it like this:

```
$SHIPIT_HOST=example.com shipit
```

**Comment by yitang** [comment]
That works nicely. Thank you.
